### PR TITLE
Fix devel builds for libdeflate

### LINKED ISSUE #194: R-devel tests failing for Ubuntu 22, Debian 11/12
Tests are failing for the R-devel builds on Ubuntu 22 and Debian 11/12 due to the libdeflate change. See https://github.com/rstudio/r-builds/pull/185

The binaries are built fine. It's just that `-ldeflate` ends up as one of the `R CMD --ldflags` flags which would cause some packages to fail to build from source.

https://github.com/rstudio/r-builds/actions/runs/6385755838/job/17332172369?pr=182
```sh
* installing *source* package 'testpkg' ...
** using staged installation
** libs
using C compiler: 'gcc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0'
using Fortran compiler: 'GNU Fortran (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0'
using C++ compiler: 'g++ (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0'
using C++11
gcc -I"/opt/R/devel/lib/R/include" -DNDEBUG   -I/usr/local/include    -fpic  -g -O2  -c add.c -o add.o
gcc -I"/opt/R/devel/lib/R/include" -DNDEBUG   -I/usr/local/include    -fpic  -g -O2  -c init.c -o init.o
gfortran  -fpic  -g -O2  -c square.f -o square.o
g++ -std=gnu++11 -I"/opt/R/devel/lib/R/include" -DNDEBUG   -I/usr/local/include    -fpic  -g -O2  -c subtract.cpp -o subtract.o
g++ -std=gnu++11 -shared -L/opt/R/devel/lib/R/lib -L/usr/local/lib -o testpkg.so add.o init.o square.o subtract.o -Wl,--export-dynamic -fopenmp -L/usr/local/lib -L/opt/R/devel/lib/R/lib -lR -lpcre2-8 -ldeflate -llzma -lbz2 -lz -ltirpc -lrt -ldl -lm -licuuc -licui18n -llapack -lblas -fopenmp -lgfortran -lm -lquadmath -L/opt/R/devel/lib/R/lib -lR
/usr/bin/ld: cannot find -ldeflate: No such file or directory
collect2: error: ld returned 1 exit status
make: *** [/opt/R/devel/lib/R/share/make/shlib.mk:10: testpkg.so] Error 1
ERROR: compilation failed for package 'testpkg'
* removing '/tmp/Rtmp8K2VuF/testpkg'
Warning message:
In install.packages(file.path(curr_dir, "testpkg"), repos = NULL,  :
  installation of package '/r-builds/test/testpkg' had non-zero exit status
Error in library(testpkg) : there is no package called 'testpkg'
Calls: source -> withVisible -> eval -> eval -> library
Execution halted
1
make: *** [Makefile:58: test-r-ubuntu-2204] Error 1
Error: Process completed with exit code 2.
```

### PR DESCRIPTION
**Pull request by gaborcsardi**
Closes #194.

### CODE REVIEW

**Comment by gaborcsardi** [comment]
The failures are fixed in #205.

**Comment by gaborcsardi** [comment]
Actually, we also need this for Debian-11 and Debian-12, I'll submit another PR.
