### ISSUE TITLE
R-devel does not compile on Ubuntu 18.04, possibly others

### ISSUE THREAD

**Issue by gaborcsardi** [rstudio/r-builds#153]
The last R-devel build for Ubuntu 18.04 is from 2023-01-04, possibly because of this: https://github.com/wch/r-source/commit/71136eccddac0e836c87ea7b77b5fc43d48cbd78

I _think_ this affects (only tested Ubuntu 18.04 explicitly):
- Ubuntu 18.04 (EOL at April 30 2023),
- CentOS 7 (maintenance updates until 2024-06-30)
- OpenSUSE 15.3 (EOL already at the end of 2022)
- OpenSUSE 15.4 (EOL at end of November 2023)

Compilation fails like this on Ubuntu 18.04:
```
* installing *source* package 'MASS' ...
** package 'MASS' successfully unpacked and MD5 sums checked
** using non-staged installation
** libs
using C compiler: 'gcc (Ubuntu/Linaro 7.5.0-3ubuntu1~18.04) 7.5.0'
make[3]: Entering directory '/tmp/RtmpjT1xnC/R.INSTALL90284ed01b1b/MASS/src'
gcc -std=gnu17 -I"/root/R-devel/include" -DNDEBUG   -I/usr/local/include    -fPIC  -g -O2  -c MASS.c -o MASS.o
gcc: error: unrecognized command line option '-std=gnu17'; did you mean '-std=gnu11'?
/root/R-devel/etc/Makeconf:184: recipe for target 'MASS.o' failed
make[3]: *** [MASS.o] Error 1
make[3]: Leaving directory '/tmp/RtmpjT1xnC/R.INSTALL90284ed01b1b/MASS/src'
ERROR: compilation failed for package 'MASS'
```

Should we do anything about this? Should we email R-core? Or patch R ourselves?

The new version of R will probably come out around the end of April, so for that only CentOS 7 (well, maintenance), and OpenSUSE 15.4 will be affected.

**Comment by glin** [comment]
From the commit message, "force C17 until mgcv gets updated", do you think it'll be a temporary failure? If not, then yeah that seems quite bad to have so many still supported distros unable to compile.

I had also been looking at another R-devel failure with openSUSE 15.3/15.4 (and probably CentOS 7) a while back, and hoping that was a bug that would be fixed at some point. But since we're getting close to April, it might be time to look more into it and ask about it as well. I wonder if you've also seen or know about a compilation error like this, seemingly related to the change with the internally-included BLAS/LAPACK:
```sh
# openSUSE 15.3/15.4
gcc -shared -L"../../../lib" -L/usr/local/lib -o R_de.so dataentry.o -lSM -lICE -lpangocairo-1.0 -lpango-1.0 -lgobject-2.0 -lglib-2.0 -lharfbuzz -lpng16 -lz -lcairo -lX11 -lXext -lX11 -lXt -lXmu  -lR -lm 
make[4]: Leaving directory '/tmp/R-devel/src/modules/X11'
make[4]: Entering directory '/tmp/R-devel/src/modules/X11'
make[4]: Leaving directory '/tmp/R-devel/src/modules/X11'
make[3]: Leaving directory '/tmp/R-devel/src/modules/X11'
gcc -shared -fopenmp -L/usr/local/lib -o libRlapack.so dlamch.o dlapack.o cmplx.o dlartg.o dlassq.o la_constants.o la_xisnan.o zlartg.o zlassq.o   -L"../../../lib" -lRblas -lgfortran -lm -lquadmath 
/usr/lib64/gcc/x86_64-suse-linux/7/../../../../x86_64-suse-linux/bin/ld: zlassq.o: warning: relocation against `__la_xisnan_MOD_disnan' in read-only section `.text'
/usr/lib64/gcc/x86_64-suse-linux/7/../../../../x86_64-suse-linux/bin/ld: dlassq.o: relocation R_X86_64_PC32 against symbol `__la_xisnan_MOD_disnan' can not be used when making a shared object; recompile with -fPIC
/usr/lib64/gcc/x86_64-suse-linux/7/../../../../x86_64-suse-linux/bin/ld: final link failed: bad value
collect2: error: ld returned 1 exit status
make[4]: *** [Makefile:104: libRlapack.so] Error 1
```
Forcing use of the external system BLAS/LAPACK with `--with-blas --with-lapack` fixes the error, but removes portability of the binaries since BLAS can no longer be swapped out. I think Fedora/EPEL's R package would hit the same compilation error.

**Comment by gaborcsardi** [comment]
> From the commit message, "force C17 until mgcv gets updated", do you think it'll be a temporary failure? If not, then yeah that seems quite bad to have so many still supported distros unable to compile.

It is probably temporary. We can wait a bit, and email them in a month or so? I don't think many people are affected by R-devel not being available on their platforms. OTOH it would nice to have a fix for R 4.3.0.

**Comment by gaborcsardi** [comment]
This is still an issue, so I am going to post to R-devel.

**Comment by gaborcsardi** [comment]
OTOH, on Ubuntu 18.04 one can instal gcc-8, and then R compiles. I'll check the other distros as well. If they also have gcc-8, then can just use that.

**Comment by gaborcsardi** [comment]
R-devel now requires libcurl 7.32.0, apparently, so that's another problem for CentOS 7. :(

**Comment by gaborcsardi** [comment]
For the record, https://mirror.city-fan.org/ftp/contrib/sysutils/Mirroring/ has newer libcurl for CentOS 7, but for x86_64 only.

**Comment by glin** [comment]
For CentOS 7, I think devtoolset is fine, and we already use devtoolset-8 to build binary packages for CentOS 7 in Package Manager. But it might make installation tough for some admins who can't install the devtoolset. The libcurl issue sounds much worse though if users would now have to download a 3rd party RPM or compile from source. Could we statically link libcurl into R? :thinking: 

Or I wonder if it'd be okay to end the CentOS 7 builds here since the EOL is next year. I know there are still RHEL 7 users that would miss it, but this is almost like R has dropped support for CentOS/RHEL 7.

**Comment by gaborcsardi** [comment]
Yeah, the centos 7 situation is not great. It is still supported until June 2024, so another bigger R release will come out before its EOL.

We can try to statically link libcurl, it might work, it might not. Let me try.

**Comment by gaborcsardi** [comment]
OK, that libcurl build that I linked also links to bunch of updated dependent libraries, so that is not great. We could try to use only a slightly newer libcurl and link to it statically.

**Comment by gaborcsardi** [comment]
Although they also have libcurl-minimal, that could be enough.
